version: "3.8"

services:
  whatsappbot:
    build: .
    container_name: whatsappbot
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./data:/app/data
    environment:
      - PUPPETEER_CACHE_DIR=/app/.cache
      - PUPPETEER_SKIP_DOWNLOAD=false
